"""shortlist by company

Revision ID: 00be8d7e6489
Revises: 88c498f4eae3
Create Date: 2025-11-17 04:51:59.476341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00be8d7e6489'
down_revision: Union[str, Sequence[str], None] = '88c498f4eae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'job_descriptions', 'companies', ['company_id'], ['id'])
    op.drop_constraint(op.f('shortlist_shortlisted_by_fkey'), 'shortlist', type_='foreignkey')
    op.create_foreign_key(None, 'shortlist', 'companies', ['shortlisted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortlist', type_='foreignkey')
    op.create_foreign_key(op.f('shortlist_shortlisted_by_fkey'), 'shortlist', 'users', ['shortlisted_by'], ['user_id'])
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.drop_column('job_descriptions', 'company_id')
    # ### end Alembic commands ###
