"""user and resume table

Revision ID: 3e5bde0c7863
Revises: 
Create Date: 2025-11-16 18:16:15.575333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5bde0c7863'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
        sa.Column('resume_id', sa.UUID(), nullable=False),
        sa.Column('uploaded_path', sa.String(length=255), nullable=False),
        sa.Column('actual_name', sa.String(length=255), nullable=False),
        sa.Column('file_format', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('resume_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table('resumes')
    # ### end Alembic commands ###
