"""candidate & company model columns add

Revision ID: 72e16451a9e8
Revises: 15139ad43283
Create Date: 2025-11-17 01:12:10.074727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e16451a9e8'
down_revision: Union[str, Sequence[str], None] = '15139ad43283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'companies', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'password')
    op.drop_column('companies', 'email')
    op.drop_column('candidates', 'department')
    # ### end Alembic commands ###
